name       : perl-alien-build
version    : 2.80
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Build-2.80.tar.gz : d9edc936b06705bb5cb5ee5a2ea8bcf6111a3e8815914f177e15e3c0fed301f3
homepage   : https://metacpan.org/dist/Alien-Build
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Build external dependencies for use in CPAN
description: |
    Build external dependencies for use in CPAN
builddeps  :
    - perl-file-which
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
